### ISSUE TITLE
Can't uglify my project with rgb-hex as a dependency

### ISSUE THREAD

**Issue by mahcloud** [sindresorhus/rgb-hex#4]
I'm running UglifyJS which is a very standard library.
I get the following error:

Parse error at index.js:3,43
ule.exports = (red, green, blue, alpha) => {

SyntaxError: Invalid assignment
    at JS_Parse_Error.Object.defineProperty.get (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /usr/local/lib/node_modules/uglify-js/bin/uglifyjs:384:39
    at time_it (/usr/local/lib/node_modules/uglify-js/bin/uglifyjs:620:15)
    at /usr/local/lib/node_modules/uglify-js/bin/uglifyjs:345:9
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

**Comment by SamVerschueren** [comment]
As pointed out in tbe PR, we aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446
